// convert-images.js  (run with: node convert-images.js)
const fs   = require('fs');
const path = require('path');

// ── Map each image filename to the key used in recipes.ts ──────────────────
const IMAGE_MAP = {
  // Hair Masks
  'avocado-hair-mask.jpg':      'avocadoHairMask',
  'egg-argan-mask.jpg':         'eggArganProteinMask',
  'coconut-milk-mask.jpg':      'coconutMilkMask',
  'banana-honey-mask.jpg':      'bananaHoneyMask',
  'castor-oil-mask.jpg':        'castorOilMask',
  'rice-water-rinse.jpg':       'riceWaterRinse',

  // Smoothies
  'green-detox-smoothie.jpg':   'greenDetoxSmoothie',
  'coconut-banana-smoothie.jpg':'coconutBananaSmoothie',
  'berry-blast-smoothie.jpg':   'berryAntioxidantSmoothie',
  'turmeric-smoothie.jpg':      'turmericGlowSmoothie',
  'mango-collagen-smoothie.jpg':'mangoCollagenSmoothie',

  // Detox Waters
  'cucumber-mint-water.jpg':    'cucumberMintWater',
  'rose-strawberry-water.jpg':  'roseStrawberryWater',
  'lemon-ginger-water.jpg':     'lemonGingerWater',
  'watermelon-basil-water.jpg': 'watermelonBasilWater',
  'acv-detox-water.jpg':        'acvDetoxWater',
  'hibiscus-berry-water.jpg':   'hibiscusBerryWater',
  'charcoal-lemon-water.jpg':   'charcoalLemonWater',
  'aloe-coconut-water.jpg':     'aloeCoconutWater',
};

const INPUT_DIR   = path.join(__dirname, 'src', 'data', 'images', 'raw');  // ✅ reads from raw/
const OUTPUT_FILE = path.join(__dirname, 'src', 'data', 'images.ts');       // ✅ writes to src/data/images.ts

// ── Convert each file to base64 ────────────────────────────────────────────
const entries = Object.entries(IMAGE_MAP).map(([filename, key]) => {
  const filepath = path.join(INPUT_DIR, filename);

  if (!fs.existsSync(filepath)) {
    console.warn(`⚠️  Missing: ${filename} — add this file to src/data/images/raw/`);
    return `  ${key}: '',  // ⚠️ MISSING: ${filename}`;
  }

  const ext     = path.extname(filename).slice(1).replace('jpg', 'jpeg');
  const b64     = fs.readFileSync(filepath).toString('base64');
  const dataURI = `data:image/${ext};base64,${b64}`;

  console.log(`✅  Converted: ${filename}  →  ${key}`);
  return `  ${key}: '${dataURI}',`;
});

// ── Write output file ──────────────────────────────────────────────────────
const output = `// ─────────────────────────────────────────────────────────────────
// Auto-generated by convert-images.js — DO NOT edit manually
// To regenerate: node convert-images.js
// ─────────────────────────────────────────────────────────────────

export const IMAGES: Record<string, string> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf8');
console.log(`\n✅  Written to: ${OUTPUT_FILE}`);
console.log(`⚠️  Restart Vite after regenerating: npm run dev`);