import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { CATEGORY_LABEL } from '../data/filters';
export const RecipeModal = ({ recipe, onClose }) => {
    const [activeStep, setActiveStep] = useState(0);
    useEffect(() => { setActiveStep(0); }, [recipe?.id]);
    if (!recipe)
        return null;
    return (_jsx("div", { className: "overlay", onClick: onClose, children: _jsxs("div", { className: "modal", onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "modal-hero", children: [_jsx("img", { src: recipe.image, alt: recipe.title }), _jsx("div", { className: "modal-hero-overlay" }), _jsx("button", { className: "modal-close", onClick: onClose, children: "\u2715" })] }), _jsxs("div", { className: "modal-content", children: [_jsxs("div", { className: "modal-meta", children: [_jsx("span", { className: "modal-cat", children: CATEGORY_LABEL[recipe.category] }), _jsx("span", { className: "modal-sep", children: "\u00B7" }), _jsxs("span", { className: "modal-time", children: ["\u23F1 ", recipe.time] }), _jsx("span", { className: "modal-diff", children: recipe.difficulty })] }), _jsx("h2", { className: "modal-title", children: recipe.title }), _jsx("div", { className: "modal-benefits", children: recipe.benefits.map((b) => (_jsx("span", { className: "modal-benefit-chip", children: b }, b))) }), _jsx("p", { className: "modal-desc", children: recipe.description }), _jsx("div", { className: "section-label", children: "Ingredients" }), _jsx("div", { className: "ingredients-grid", children: recipe.ingredients.map((ing) => (_jsxs("div", { className: "ing-card", children: [_jsx("span", { className: "ing-emoji", children: ing.emoji }), _jsxs("div", { children: [_jsx("div", { className: "ing-name", children: ing.name }), _jsx("div", { className: "ing-benefit", children: ing.benefit })] })] }, ing.name))) }), _jsx("div", { className: "section-label", children: "Steps \u2014 tap to track progress" }), _jsx("div", { className: "steps-list", children: recipe.steps.map((step, i) => (_jsxs("div", { className: `step ${i === activeStep ? 'active' : ''} ${i < activeStep ? 'done' : ''}`, onClick: () => setActiveStep(i === activeStep ? i + 1 : i), children: [_jsx("div", { className: "step-num", children: i < activeStep ? '✓' : i + 1 }), _jsx("div", { className: "step-text", children: step })] }, i))) })] })] }) }));
};
