import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams, Link, Navigate } from 'react-router';
import { recipes } from '../data/recipes';
const CATEGORY_LABEL = {
    'hair-mask': 'Hair Masks',
    'smoothie': 'Smoothies',
    'detox-water': 'Detox Waters',
};
export function RecipeDetail() {
    const { id } = useParams();
    if (!id)
        return _jsx(Navigate, { to: "/", replace: true });
    const recipe = recipes.find((r) => r.id === Number(id));
    if (!recipe)
        return _jsx(Navigate, { to: "/", replace: true });
    const related = recipes
        .filter((r) => r.category === recipe.category && r.id !== recipe.id)
        .slice(0, 3);
    return (_jsxs("div", { className: "max-w-4xl mx-auto px-4 py-12", children: [_jsx(Link, { to: "/", className: "text-sm text-emerald-600 hover:underline mb-6 inline-block", children: "\u2190 Back to Recipes" }), _jsx("div", { className: "rounded-2xl overflow-hidden mb-8 aspect-[16/7]", children: _jsx("img", { src: recipe.image, alt: recipe.title, className: "w-full h-full object-cover" }) }), _jsxs("div", { className: "flex flex-wrap gap-2 mb-4", children: [_jsx("span", { className: "bg-emerald-100 text-emerald-700 text-sm px-3 py-1 rounded-full", children: CATEGORY_LABEL[recipe.category] }), _jsx("span", { className: "bg-gray-100 text-gray-600 text-sm px-3 py-1 rounded-full capitalize", children: recipe.difficulty }), _jsxs("span", { className: "bg-gray-100 text-gray-600 text-sm px-3 py-1 rounded-full", children: ["\u23F1 ", recipe.time, "                                   "] })] }), _jsx("h1", { className: "text-4xl font-semibold mb-4", children: recipe.title }), _jsx("p", { className: "text-gray-600 text-lg mb-8", children: recipe.description }), _jsxs("div", { className: "bg-emerald-50 rounded-xl p-6 mb-8", children: [_jsx("h2", { className: "font-semibold text-lg mb-3", children: "Benefits" }), _jsx("div", { className: "flex flex-wrap gap-2", children: recipe.benefits.map(b => (_jsx("span", { className: "bg-white text-emerald-700 border border-emerald-200\n                                     text-sm px-3 py-1 rounded-full capitalize", children: b.replace(/-/g, ' ') }, b))) })] }), _jsxs("div", { className: "grid md:grid-cols-2 gap-8 mb-8", children: [_jsxs("div", { className: "bg-white rounded-xl border p-6", children: [_jsx("h2", { className: "font-semibold text-lg mb-4", children: "Ingredients" }), _jsx("div", { className: "space-y-3", children: recipe.ingredients.map((ing) => (_jsxs("div", { className: "flex gap-3", children: [_jsx("span", { className: "text-2xl", children: ing.emoji }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-sm", children: ing.name }), _jsx("p", { className: "text-xs text-gray-500", children: ing.benefit })] })] }, ing.name))) })] }), _jsxs("div", { className: "bg-white rounded-xl border p-6", children: [_jsx("h2", { className: "font-semibold text-lg mb-4", children: "Instructions" }), _jsx("ol", { className: "space-y-3", children: recipe.steps.map((step, i) => ( // ✅ YOUR field
                                _jsxs("li", { className: "flex gap-3 text-sm text-gray-700", children: [_jsx("span", { className: "flex-shrink-0 w-6 h-6 bg-emerald-600 text-white\n                                 rounded-full flex items-center justify-center text-xs font-bold", children: i + 1 }), step] }, i))) })] })] }), _jsx("div", { className: "bg-amber-50 border border-amber-100 rounded-xl p-6 mb-8", children: _jsxs("p", { className: "text-sm text-amber-800", children: ["\uD83D\uDCA1 ", _jsx("strong", { children: "Pro Tip:" }), " Always patch test new ingredients before full application."] }) }), related.length > 0 && (_jsxs("div", { children: [_jsxs("h2", { className: "font-semibold text-lg mb-4", children: ["More ", CATEGORY_LABEL[recipe.category]] }), _jsx("div", { className: "grid sm:grid-cols-3 gap-4", children: related.map((r) => (_jsxs(Link, { to: `/recipes/${r.id}`, className: "bg-white rounded-xl border overflow-hidden hover:shadow-md transition-shadow", children: [_jsx("img", { src: r.image, alt: r.title, className: "w-full h-32 object-cover" }), _jsxs("div", { className: "p-3", children: [_jsx("p", { className: "text-sm font-medium line-clamp-2", children: r.title }), _jsx("p", { className: "text-xs text-gray-400 mt-1", children: r.time }), "  "] })] }, r.id))) })] }))] }));
}
